// Generates dist/sw.js after each build: a small service worker that keeps
// the site usable offline — handy at events, where coverage is often poor
// and someone who tapped the NFC tag wants to look at it again later.
//
// - Precache (in the background, after the first visit): every page's HTML,
//   all JS/CSS, and the "latin" font files the pages actually use. Not the
//   images (~2MB of screenshot variants): those are cached as they're seen.
// - Pages: network first, so nobody sees stale content; the cached copy is
//   used when offline or when the network takes more than 4s.
// - Hashed assets (/_astro/…) and images: cache first.
// - Only same-origin GETs are handled; analytics etc. pass straight through.
// Each build gets its own cache name (hash of the precache list), and old
// caches are deleted when the new worker activates.
import { createHash } from "node:crypto";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

export default function serviceWorker() {
  let base = "/";
  return {
    name: "pacomolina-service-worker",
    hooks: {
      "astro:config:done": ({ config }) => {
        base = config.base.endsWith("/") ? config.base : `${config.base}/`;
      },
      "astro:build:done": ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const files = walk(root).map((f) => relative(root, f).split(sep).join("/"));

        const pages = files
          .filter((f) => f.endsWith("index.html"))
          .map((f) => base + f.replace(/index\.html$/, ""));
        const assets = files.filter(
          (f) =>
            (f.startsWith("_astro/") && /\.(js|css)$/.test(f)) ||
            // Only the latin subset of the two weights in use: other subsets
            // are declared but never downloaded (see global.css).
            (f.startsWith("_astro/") && /-latin-(400|500)-normal\.[^.]+\.woff2$/.test(f))
        );
        const precache = [...pages, ...assets.map((f) => base + f), `${base}manifest.webmanifest`];
        const version = createHash("sha256").update(precache.join("\n")).digest("hex").slice(0, 12);

        const sw = `// Generated by src/integrations/service-worker.mjs — don't edit.
const CACHE = "pacomolina-${version}";
const PRECACHE = ${JSON.stringify(precache)};
const PAGE_TIMEOUT = 4000;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("pacomolina-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function networkFirst(request) {
  return new Promise((resolve) => {
    let settled = false;
    const fromCache = () =>
      caches
        .match(request, { ignoreSearch: true, ignoreVary: true })
        .then((hit) => hit || caches.match("${base}", { ignoreVary: true }));
    const timer = setTimeout(() => {
      fromCache().then((hit) => {
        if (hit && !settled) {
          settled = true;
          resolve(hit);
        }
      });
    }, PAGE_TIMEOUT);
    fetch(request)
      .then((response) => {
        clearTimeout(timer);
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        if (!settled) {
          settled = true;
          resolve(response);
        }
      })
      .catch(() => {
        clearTimeout(timer);
        fromCache().then((hit) => {
          if (!settled) {
            settled = true;
            resolve(hit || Response.error());
          }
        });
      });
  });
}

function cacheFirst(request) {
  // ignoreVary: servers answer with Vary (Origin, Accept-Encoding…), and a
  // module/font request carries headers the precache request didn't, so a
  // strict match would miss what's already cached.
  return caches.match(request, { ignoreVary: true }).then(
    (hit) =>
      hit ||
      fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      })
  );
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request));
  } else if (url.pathname.startsWith("${base}_astro/") || /\\.(webp|jpe?g|png|svg|woff2)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(request));
  }
});
`;
        writeFileSync(join(root, "sw.js"), sw);
        logger.info(`sw.js: ${pages.length} pages + ${assets.length} assets precached (cache ${version})`);
      },
    },
  };
}
